Update patch set 6
Patch Set 6:

The failures are due to:

	TypeError: Cannot read property 'val' of null
	    at OoUiMenuSelectWidget.OO.ui.MenuSelectWidget.updateItemVisibility (dist/oojs-ui-core.js:9:234006)

Patch-set: 6
Reviewer: Catrope <5@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0