Avoid empty insert in SqlScoreStorage::storeScores
UnexpectedValueException: Wikimedia\Rdbms\InsertQueryBuilder::execute
can't have empty $rows value

Bug: T364218
Change-Id: Ic5d0b688cf13df18bc71dc70da4da2685d70830d
(cherry picked from commit 3179045b57baf8936ca326e5ba5d987198f4dae4)